networks:
  default: localnet
  localnet:
    id: 61127
    url: http://127.0.0.1:4000/api
    leader_only: false
  studionet:
    id: 61999
    url: https://studio.genlayer.com/api
    leader_only: false
paths:
  contracts: contracts
  artifacts: artifacts
